BEGIN 

EXECUTE IMMEDIATE 'DROP TABLE RATING CASCADE CONSTRAINTS';
EXECUTE IMMEDIATE 'DROP TABLE CLIENT CASCADE CONSTRAINTS';
EXECUTE IMMEDIATE 'DROP TABLE CARD_CHANGE_TIME CASCADE CONSTRAINTS';
EXECUTE IMMEDIATE 'DROP TABLE LOG_READING_ROOM CASCADE CONSTRAINTS';
EXECUTE IMMEDIATE 'DROP TABLE PUBLISHER CASCADE CONSTRAINTS';
EXECUTE IMMEDIATE 'DROP TABLE BOOK_TYPE CASCADE CONSTRAINTS';
EXECUTE IMMEDIATE 'DROP TABLE BOOK CASCADE CONSTRAINTS';
EXECUTE IMMEDIATE 'DROP TABLE EXEMPLAR CASCADE CONSTRAINTS';
EXECUTE IMMEDIATE 'DROP TABLE LOG_DELIVERY_RETURN_BOOK CASCADE CONSTRAINTS';
EXECUTE IMMEDIATE 'DROP TABLE LOG_ADD_DELETE_BOOK CASCADE CONSTRAINTS';
EXECUTE IMMEDIATE 'DROP TABLE TAG CASCADE CONSTRAINTS';
EXECUTE IMMEDIATE 'DROP TABLE BOOK_HAVE_TAG CASCADE CONSTRAINTS';
EXECUTE IMMEDIATE 'DROP TABLE AUTHOR CASCADE CONSTRAINTS';
EXECUTE IMMEDIATE 'DROP TABLE AUTHOR_WROTE_BOOK CASCADE CONSTRAINTS';
EXECUTE IMMEDIATE 'DROP TABLE GENRE CASCADE CONSTRAINTS';
EXECUTE IMMEDIATE 'DROP TABLE BOOK_HAVE_GENRE CASCADE CONSTRAINTS';
EXECUTE IMMEDIATE 'DROP TABLE PREFERENCE CASCADE CONSTRAINTS';

EXECUTE IMMEDIATE 'DROP SEQUENCE BOOK_ID_SEQ';

END;







select 'drop table ' || table_name || ';' from user_tables
select 'drop sequence ' || sequence_name || ';' from user_sequences;

drop package book_pkg
drop package client_pkg
drop package report_pkg

BEGIN

  --Bye Tables!
  FOR i IN (SELECT ut.table_name
              FROM USER_TABLES ut) LOOP
    EXECUTE IMMEDIATE 'drop table '|| i.table_name ||' CASCADE CONSTRAINTS ';
  END LOOP;

END;

PURGE RECYCLEBIN; 
COMMIT;

BEGIN

  --Bye Tables!
  FOR i IN (SELECT ut.sequence_name
              FROM user_sequences ut) LOOP
    EXECUTE IMMEDIATE 'drop sequence '|| i.sequence_name ;
  END LOOP;

END;