CREATE OR REPLACE TRIGGER CHECK_YEAR_OF_PUBLICATION
    BEFORE INSERT OR UPDATE ON BOOK
    FOR EACH ROW
BEGIN

    IF :NEW.YEAR_OF_PUBLICATION NOT BETWEEN 1000 AND EXTRACT(YEAR FROM SYSDATE)
        THEN
            RAISE_APPLICATION_ERROR(-20500, 'Неверный год публикации');
    END IF;
END;